[package]
name = "rust_tracing"
version = "0.1.0"
authors = ["MacGamerFR <tomstom-du-01@hotmail.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"