name: Build nightly

on: push

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: minimal
            components: clippy
            override: true

      - name: Cache release
        uses: actions/cache@v1
        env:
          cache-name: cache-rust
        with:
          path: target/
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features

  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: minimal
            override: true

      - name: Cache release
        uses: actions/cache@v1
        env:
          cache-name: cache-rust
        with:
          path: target/
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build an optimized executable
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Save Linux artifact
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v1
        with:
          name: yarrt-nightly-${{ runner.os }}
          path: target/release/rust_tracing

      - name: Save Windows artifact
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v1
        with:
          name: yarrt-nightly-${{ runner.os }}
          path: targeT/release/rust_tracing.exe

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            default: minimal
            components: clippy
            override: true

      - name: Cache release
        uses: actions/cache@v1
        env:
          cache-name: cache-rust
        with:
          path: target/
          key: ${{ runner.os }}-build-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-
