name: Rust

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
        name: [linux, win]
    runs-on: ${{matrix.platform}}
    steps:
    - uses: actions/checkout@v2

    - name: Cache release
      uses: actions/cache@v1
      env:
        cache-name: cache-rust
      with:
        path: target/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
        restore-keys: |
           ${{ runner.os }}-build-${{ env.cache-name }}-
           ${{ runner.os }}-build-
           ${{ runner.os }}-

    - name: Build
      run: cargo build --release --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Save artifact
      uses: actions/upload-artifact@v1
      with:
        name: yarrt-nightly-${{matrix.name}}
        path: target/release/rust_tracing
